---
- name: Instalação e Configuração do Docker Storage
  hosts: nodes

  vars:
    docker_version: 1.13.1
    docker_storage_disk: sdb

  tasks:
    - name: Parando o serviço Docker
      systemd:
        name: docker
        state: stopped

    - name: Removendo pacote docker
      yum:
        name: docker
        state: removed

    - name: Removendo docker-novolume-plugin
      yum:
        name: docker-novolume-plugin
        state: removed

    - name: Wipe no device
      shell: "wipefs --all --force /dev/{{ docker_storage_disk }}"

    - name: Reiniciando os hosts
      tags: reboot
      become: yes
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Aguardando pelo reboot e inicialização dos hosts
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 300

    - name: Testa a conexão dos hosts
      ping:
